# Meta data for the action.

name: 'Review App Deployment Status'
author: 'Surya Teja'
description: 'A github action for review app deployment status'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  heroku_app_name:
    description: (optional) The application name in the heroku.
    required: false
  timeout:
    description: (optional) Github Action timeout in seconds.
    required: false
    default: 300 # 5 mins
  span:
    description: (optional) Interval to check the status.
    required: false
    default: 10 # 5 mins
  statuses:
    description: (optional) statuses which can be allowed. separated by comma.
    required: false
    default: 200 # All ok status

branding:
  icon: 'activity'  
  color: 'green'
